server:
  port: 8088

env:
  credentials: 'Ftp1Lx2Y9uVqM5Q1fzAgy3kngGMWqOsUGylPGc3oYD6a3o5vSxMHC4NKE8+f1HCdo3T+ZJEBZq50BaJy9rSGh18/iBQBSUoI8MAF402kYjQ='
  fromVerkey: '6QvQ3Y5pPMGNgzvs86N3AQo98pF5WrzM1h6WkKH3dL7f'
  fromSigKey: '28Au6YoU7oPt6YLpbWkzFryhaQbfAcca9KxZEmz22jJaZoKqABc4UJ9vDjNTtmKSn2Axfu8sT52f5Stmt7JD4zzh'
  thierKey: '4PQsX8fuBguerSaBbTQuGhtS8rgCz82XJmeTFM9VGPFj'
  serverUrl: 'http://localhost'